### PR TITLE
Add a field stop in the coronagraph.

### PR DESCRIPTION
**Pull request by ehpor**
WIP

## Tasks
- [x] Needs to be tested (so far I haven't run any code).

### CODE REVIEW

**Comment by ehpor** [comment]
I'm seeing some manual MFTs inside the analysis scripts. AFAIK they are for throughput calculations only, so they should not be impacted by any changes make in this PR.

**Comment by ehpor** [comment]
I did a search for `LyotCoronagraph` (ie. the HCIPy version without field stop) and it's not being used anymore.

**Comment by ehpor** [comment]
With and without field stop for a random hex aperture.

image

**Comment by ehpor** [comment]
Tested and working. Ready for review.

**Comment by brynickson** [comment]
LGTM.

**Pull request merged**
